title: Saepul Hilal
<img src="/images/IMG_5415.JPG?raw=true" alt="Foto Profil" style="width:240px; height:240px; object-fit:cover; border-radius:50%; display:block; margin:20px 0;">
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>
  Data Scientist with 4+ years of commercial experience in analytics, strategy and sales and a master's degree in Data Science from Oxford University. Previously at Vodafone, VIMA Group (management consulting), Ovo Energy, HSBC.
  <br><br>
  Ranked in top 10% of undergraduate cohort at Cambridge University.
  <br><br>
  <a href="https://www.linkedin.com/in/saepul-hilal/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
