title: Saepul Hilal
description: > # your text below (remove <br> elements if you don't need line breaks)
  <div style="text-align: justify;">
    <img src="/images/profile300.png" alt="Foto Profil" style="width:200px; height:200px; display:block; margin:20px auto;">

    <br>
    Data Scientist with 1+ years of professional experience in analytics, machine learning, and AI Development. Bachelor’s degree in Information Systems from University Ary Ginanjar. Currently delivering business impact at Mediawave Interaktif through political analytics, media sentiment modeling, LLM prompt optimization, and nutrition recommendation projects. 
    <br><br>
    Graduated with distinction from University Ary Ginanjar (GPA 3.67/4.00) and achieved a 91% score in Hacktiv8 Data Science Bootcamp.
    <br><br>
  </div>
  <div style="display: flex; gap: 15px; align-items: center;">
    <!-- LinkedIn -->
    <a href="https://www.linkedin.com/in/saepul-hilal/" target="_blank" title="LinkedIn">
      <img src="https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/linkedin.svg" alt="LinkedIn" style="width:28px; height:28px; filter: grayscale(1);">
    </a>
    <!-- GitHub -->
    <a href="https://github.com/saepulhilal" target="_blank" title="GitHub">
      <img src="https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/github.svg" alt="GitHub" style="width:28px; height:28px; filter: grayscale(1);">
    </a>
    <!-- Email -->
    <a href="mailto:saepulhilal691@gmail.com" target="_blank" title="Email">
      <img src="https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/gmail.svg" alt="Email" style="width:28px; height:28px; filter: grayscale(1);">
    </a>
    <!-- WhatsApp -->
    <a href="https://wa.me/6285157116691" target="_blank" title="WhatsApp">
      <img src="https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/whatsapp.svg" alt="WhatsApp" style="width:28px; height:28px;">
    </a>
  </div>

theme: jekyll-theme-minimal
google_analytics: G-JBY55YSQ77 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
